const orders=[{id:'ORD-10245',product:'Nike Air Max 270',qty:1,total:'₦85,000',date:'Sep 14, 2026',status:'Out for delivery',tracking:'NG123456789',eta:'Sep 16, 2026',address:'14 Allen Avenue, Ikeja, Lagos',icon:'👟',history:[['Order placed','Sep 14 · 9:24 AM'],['Payment confirmed','Sep 14 · 9:27 AM'],['Order shipped','Sep 15 · 7:40 AM'],['Out for delivery','Sep 16 · 8:12 AM'],['Delivered','Pending']]},{id:'ORD-10191',product:'Wireless Headphones',qty:1,total:'₦42,500',date:'Aug 29, 2026',status:'Delivered',tracking:'NG987654321',eta:'Sep 2, 2026',address:'14 Allen Avenue, Ikeja, Lagos',icon:'🎧',history:[['Order placed','Aug 29 · 10:10 AM'],['Payment confirmed','Aug 29 · 10:12 AM'],['Order shipped','Aug 30 · 8:00 AM'],['Out for delivery','Sep 2 · 8:15 AM'],['Delivered','Sep 2 · 2:06 PM']]},{id:'ORD-10084',product:'Classic Leather Backpack',qty:1,total:'₦55,000',date:'Aug 10, 2026',status:'Delivered',tracking:'NG456789123',eta:'Aug 14, 2026',address:'14 Allen Avenue, Ikeja, Lagos',icon:'🎒',history:[['Order placed','Aug 10 · 2:11 PM'],['Payment confirmed','Aug 10 · 2:13 PM'],['Order shipped','Aug 11 · 9:30 AM'],['Out for delivery','Aug 14 · 7:50 AM'],['Delivered','Aug 14 · 12:21 PM']]}];
let page='dashboard', selected=orders[0];
const app=document.getElementById('app');
function login(){app.innerHTML=`<div class="login"><div class="loginbox"><div class="brand">West<span>Cart</span></div><h1 style="margin-top:24px">Welcome back</h1><p class="muted">Sign in to view your orders and delivery tracking.</p><div class="field"><label>Email address</label><input id="email" value="taye@example.com" type="email"></div><div class="field"><label>Password</label><input id="pass" value="password" type="password"></div><button class="btn full" onclick="enter()">Sign in</button><div class="notice">Demo account: any email and password will work.</div></div></div>`}
function enter(){render()}
function render(){app.innerHTML=`<header class="top"><div class="brand">West<span>Cart</span></div><div class="topright"><span class="muted">Taye West</span><div class="avatar">TW</div></div></header><div class="layout"><aside><nav class="nav"><button class="${page==='dashboard'?'active':''}" onclick="go('dashboard')">▦ &nbsp; Dashboard</button><button class="${page==='orders'?'active':''}" onclick="go('orders')">▤ &nbsp; My Orders</button><button class="${page==='tracking'?'active':''}" onclick="go('tracking')">⌁ &nbsp; Track Order</button><button onclick="go('profile')">◯ &nbsp; Profile</button><button onclick="login()">↪ &nbsp; Logout</button></nav></aside><main class="main">${content()}</main></div>`}
function content(){if(page==='dashboard')return dashboard();if(page==='orders')return ordersPage();if(page==='tracking')return tracking();return profile()}
function dashboard(){return `<section><h1 class="h1">Good evening, Taye 👋</h1><p class="muted">Here’s what’s happening with your account.</p><div class="cards"><div class="card"><span class="muted">Total orders</span><div class="metric">${orders.length}</div></div><div class="card"><span class="muted">In transit</span><div class="metric">1</div></div><div class="card"><span class="muted">Delivered</span><div class="metric">2</div></div></div><div class="grid"><div class="panel"><h3>Recent orders</h3>${orders.slice(0,2).map(o=>orderRow(o)).join('')}</div><div class="panel"><h3>Current delivery</h3><p><b>${selected.product}</b></p><p class="muted">${selected.tracking}</p><div class="track">${selected.history.slice(0,4).map((s,i)=>`<div class="step done"><div class="dot"></div><div><strong>${s[0]}</strong><span class="muted">${s[1]}</span></div></div>`).join('')}</div><button class="btn secondary" onclick="go('tracking')">View full tracking</button></div></div></section>`}
function orderRow(o){return `<div class="order"><div class="product"><div class="thumb">${o.icon}</div><div><b>${o.product}</b><div class="muted">${o.id} · ${o.date}</div></div></div><div style="text-align:right"><div><b>${o.total}</b></div><span class="pill">${o.status}</span></div><button class="btn secondary" onclick="selectOrder('${o.id}')">View</button></div>`}
function ordersPage(){return `<section><h1 class="h1">My Orders</h1><p class="muted">View your order history and delivery status.</p><div class="panel" style="margin-top:24px">${orders.map(o=>orderRow(o)).join('')}</div></section>`}
function tracking(){return `<section><button class="back" onclick="go('orders')">← Back to orders</button><h1 class="h1">Track ${selected.id}</h1><p class="muted">${selected.product} · Tracking number ${selected.tracking}</p><div class="grid" style="margin-top:24px"><div class="panel"><h3>Delivery progress</h3><div class="track">${selected.history.map((s,i)=>{let done=selected.status==='Delivered'||i<4;return `<div class="step ${done?'done':''}"><div class="dot"></div><div><strong>${s[0]}</strong><span class="muted">${s[1]}</span></div></div>`}).join('')}</div></div><div class="panel"><h3>Shipment details</h3><div class="details"><div class="kv"><small>Tracking number</small><b>${selected.tracking}</b></div><div class="kv"><small>Estimated delivery</small><b>${selected.eta}</b></div><div class="kv"><small>Delivery address</small><b>${selected.address}</b></div><div class="kv"><small>Status</small><b>${selected.status}</b></div></div></div></div></section>`}
function profile(){return `<section><h1 class="h1">My Profile</h1><p class="muted">Manage your account information.</p><div class="panel" style="margin-top:24px;max-width:650px"><div class="field"><label>Full name</label><input value="Taye West"></div><div class="field"><label>Email</label><input value="taye@example.com"></div><div class="field"><label>Phone</label><input value="+234 800 000 0000"></div><button class="btn">Save changes</button></div></section>`}
function go(p){page=p;render()}function selectOrder(id){selected=orders.find(o=>o.id===id)||orders[0];page='tracking';render()}login();
